services:
  backend:
    build:
      context: ./backend
    network_mode: host
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
      - OLLAMA_MODEL=llama3.2:latest

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    volumes: 
    - ./frontend:/app 
    - /app/node_modules 
    
      
    